import { wholeWord } from "./pattern-utils";
import { TEXT_FIELDS, type TextRule } from "./types";

// Padrões textuais associados a golpes comuns em vídeos e descrições no Brasil.
// Domínio separado (scam_context): risco de golpe nunca entra no score de
// synthetic_media — são evidências independentes (ver docs/detection-pipeline.md §5).
export const scamRules: TextRule[] = [
  {
    id: "scam-indemnity",
    domain: "scam_context",
    patterns: [wholeWord("indenização"), wholeWord("você tem direito a uma indenização")],
    fields: TEXT_FIELDS,
    weight: 0.55,
    confidence: 0.8,
    correlationGroup: "scam-indemnity",
    evidenceType: "description",
    label: "Padrão textual de golpe: indenização",
    descriptionTemplate: 'O texto contém "{match}", padrão comum em golpes de falsa indenização.',
  },
  {
    id: "scam-gov-benefit",
    domain: "scam_context",
    patterns: [
      wholeWord("saque liberado"),
      wholeWord("valor liberado"),
      wholeWord("consulte seu cpf"),
      wholeWord("benefício liberado"),
    ],
    fields: TEXT_FIELDS,
    weight: 0.6,
    confidence: 0.8,
    correlationGroup: "scam-gov-benefit",
    evidenceType: "description",
    label: "Padrão textual de golpe: benefício do governo",
    descriptionTemplate: 'O texto contém "{match}", padrão comum em golpes de falso benefício do governo.',
  },
  {
    id: "scam-investment",
    domain: "scam_context",
    patterns: [
      wholeWord("investimento garantido"),
      wholeWord("renda extra garantida"),
      wholeWord("lucro garantido"),
    ],
    fields: TEXT_FIELDS,
    weight: 0.6,
    confidence: 0.8,
    correlationGroup: "scam-investment",
    evidenceType: "description",
    label: "Padrão textual de golpe: investimento garantido",
    descriptionTemplate: 'O texto contém "{match}", padrão comum em golpes de investimento com retorno garantido.',
  },
  {
    id: "scam-pix",
    domain: "scam_context",
    patterns: [wholeWord("faça um pix"), wholeWord("faça o pix"), wholeWord("envie um pix")],
    fields: TEXT_FIELDS,
    weight: 0.5,
    confidence: 0.8,
    correlationGroup: "scam-pix",
    evidenceType: "description",
    label: "Padrão textual de golpe: pedido de Pix",
    descriptionTemplate: 'O texto contém "{match}", pedido direto de transferência via Pix.',
  },
  {
    id: "scam-loan",
    domain: "scam_context",
    patterns: [
      wholeWord("empréstimo imediato"),
      wholeWord("empréstimo sem consulta"),
      wholeWord("sem consulta ao spc"),
      wholeWord("sem consulta ao serasa"),
    ],
    fields: TEXT_FIELDS,
    weight: 0.5,
    confidence: 0.8,
    correlationGroup: "scam-loan",
    evidenceType: "description",
    label: "Padrão textual de golpe: empréstimo imediato",
    descriptionTemplate: 'O texto contém "{match}", padrão comum em golpes de empréstimo fácil.',
  },
  {
    id: "scam-urgency",
    domain: "scam_context",
    patterns: [wholeWord("últimas vagas"), wholeWord("só hoje")],
    fields: TEXT_FIELDS,
    weight: 0.4,
    confidence: 0.8,
    correlationGroup: "scam-urgency",
    evidenceType: "description",
    label: "Padrão textual de golpe: urgência artificial",
    descriptionTemplate: 'O texto contém "{match}", tática de urgência comum em golpes.',
  },
];
